backend:
  name: git-gateway
  repo: patrickbolle/ca-hexo-netlify
  branch: master # Branch to update (optional; defaults to master)

media_folder: "source/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit
    - label: "Projects"
      name: "projects"
      folder: "source/_posts/projects/"
      create: true
      fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: "galleria"
        label: "Gallery" 
        widget: "list"
        optional: true
        fields:
          - {label: "Title", name: "imgTitle", widget: "string"}
          - {label: "Gallery Image", name: "imgSrc", widget: "image"}
          - {label: "Description", name: "imgDesc", widget: "string"}